/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as virusMlmV5Sol from "./VirusMLM_V5.sol";
export type { virusMlmV5Sol };
import type * as mocks from "./mocks";
export type { mocks };
