/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VirusMLMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_REFERRAL_DEPTH"
      | "MIN_WITHDRAW"
      | "PACKETS"
      | "POOL_DISTRIBUTION_INTERVAL"
      | "POOL_SHARES"
      | "VIP_DURATION"
      | "WITHDRAW_PERCENTAGES"
      | "activatePacket"
      | "checkUpkeep"
      | "claimMatrix"
      | "claimPool"
      | "completeMultisigTransition"
      | "confirmVip"
      | "currentPhase"
      | "deploymentTime"
      | "developmentFundWallet"
      | "distributePool"
      | "donateToPool"
      | "emergencyWithdraw"
      | "gamePoolWallet"
      | "getGovernanceInfo"
      | "getMatrixNode"
      | "getPoolInfo"
      | "getQueueInfo"
      | "getUserInfo"
      | "getVipInfo"
      | "getVipList"
      | "initiateMultisigTransition"
      | "isRegistered"
      | "lastPoolDistribution"
      | "liquidityPool"
      | "matrixNodes"
      | "multisigTransitionTime"
      | "nextNodeId"
      | "owner"
      | "pendingMultisig"
      | "performUpkeep"
      | "register"
      | "reinvestFeeWallet"
      | "renewVip"
      | "renounceOwnership"
      | "requestVip"
      | "reserveWallet"
      | "revokeVip"
      | "rootId"
      | "setAntiSybilVerified"
      | "totalMatrixPayouts"
      | "totalPoolPayouts"
      | "totalReferralPayouts"
      | "totalUsers"
      | "transferOwnership"
      | "updateWallets"
      | "usdtToken"
      | "users"
      | "vipInfo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AntiSybilVerified"
      | "GovernancePhaseChanged"
      | "MatrixClaimed"
      | "MatrixPayout"
      | "MultisigTransitionCompleted"
      | "MultisigTransitionStarted"
      | "OwnershipTransferred"
      | "PacketActivated"
      | "PoolClaimed"
      | "PoolDistributed"
      | "PoolDonated"
      | "ReferralPayout"
      | "UserRegistered"
      | "VipConfirmed"
      | "VipRenewed"
      | "VipRequested"
      | "VipRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_REFERRAL_DEPTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WITHDRAW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PACKETS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_DISTRIBUTION_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_SHARES",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "VIP_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_PERCENTAGES",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activatePacket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMatrix",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeMultisigTransition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmVip",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "developmentFundWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donateToPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gamePoolWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGovernanceInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatrixNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQueueInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVipInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVipList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateMultisigTransition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPoolDistribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matrixNodes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multisigTransitionTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextNodeId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingMultisig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reinvestFeeWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renewVip",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestVip",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVip",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rootId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAntiSybilVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalMatrixPayouts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoolPayouts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralPayouts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWallets",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "vipInfo",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_REFERRAL_DEPTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WITHDRAW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PACKETS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "POOL_DISTRIBUTION_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_SHARES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VIP_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_PERCENTAGES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activatePacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMatrix",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeMultisigTransition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "confirmVip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "developmentFundWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donateToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gamePoolWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGovernanceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatrixNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQueueInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVipInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVipList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateMultisigTransition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPoolDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matrixNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multisigTransitionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextNodeId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reinvestFeeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renewVip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requestVip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reserveWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeVip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rootId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAntiSybilVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMatrixPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPoolPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vipInfo", data: BytesLike): Result;
}

export namespace AntiSybilVerifiedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernancePhaseChangedEvent {
  export type InputTuple = [oldPhase: BigNumberish, newPhase: BigNumberish];
  export type OutputTuple = [oldPhase: bigint, newPhase: bigint];
  export interface OutputObject {
    oldPhase: bigint;
    newPhase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatrixClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    toWallet: BigNumberish,
    reinvested: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    toWallet: bigint,
    reinvested: bigint
  ];
  export interface OutputObject {
    user: string;
    toWallet: bigint;
    reinvested: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatrixPayoutEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigTransitionCompletedEvent {
  export type InputTuple = [multisigAddress: AddressLike, time: BigNumberish];
  export type OutputTuple = [multisigAddress: string, time: bigint];
  export interface OutputObject {
    multisigAddress: string;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigTransitionStartedEvent {
  export type InputTuple = [
    multisigAddress: AddressLike,
    completionTime: BigNumberish
  ];
  export type OutputTuple = [multisigAddress: string, completionTime: bigint];
  export interface OutputObject {
    multisigAddress: string;
    completionTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PacketActivatedEvent {
  export type InputTuple = [
    user: AddressLike,
    packet: BigNumberish,
    time: BigNumberish
  ];
  export type OutputTuple = [user: string, packet: bigint, time: bigint];
  export interface OutputObject {
    user: string;
    packet: bigint;
    time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    toWallet: BigNumberish,
    reinvested: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    toWallet: bigint,
    reinvested: bigint
  ];
  export interface OutputObject {
    user: string;
    toWallet: bigint;
    reinvested: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolDistributedEvent {
  export type InputTuple = [
    totalAmount: BigNumberish,
    distributedPerLevel: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    reserved: BigNumberish
  ];
  export type OutputTuple = [
    totalAmount: bigint,
    distributedPerLevel: [bigint, bigint, bigint, bigint, bigint],
    reserved: bigint
  ];
  export interface OutputObject {
    totalAmount: bigint;
    distributedPerLevel: [bigint, bigint, bigint, bigint, bigint];
    reserved: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolDonatedEvent {
  export type InputTuple = [donor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [donor: string, amount: bigint];
  export interface OutputObject {
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralPayoutEvent {
  export type InputTuple = [
    sponsor: AddressLike,
    user: AddressLike,
    amount: BigNumberish,
    toPool: boolean
  ];
  export type OutputTuple = [
    sponsor: string,
    user: string,
    amount: bigint,
    toPool: boolean
  ];
  export interface OutputObject {
    sponsor: string;
    user: string;
    amount: bigint;
    toPool: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    referrer: AddressLike,
    placementId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    referrer: string,
    placementId: bigint
  ];
  export interface OutputObject {
    user: string;
    referrer: string;
    placementId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VipConfirmedEvent {
  export type InputTuple = [
    user: AddressLike,
    starLevel: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    starLevel: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    starLevel: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VipRenewedEvent {
  export type InputTuple = [
    user: AddressLike,
    starLevel: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    starLevel: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    starLevel: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VipRequestedEvent {
  export type InputTuple = [user: AddressLike, starLevel: BigNumberish];
  export type OutputTuple = [user: string, starLevel: bigint];
  export interface OutputObject {
    user: string;
    starLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VipRevokedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VirusMLM extends BaseContract {
  connect(runner?: ContractRunner | null): VirusMLM;
  waitForDeployment(): Promise<this>;

  interface: VirusMLMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_REFERRAL_DEPTH: TypedContractMethod<[], [bigint], "view">;

  MIN_WITHDRAW: TypedContractMethod<[], [bigint], "view">;

  PACKETS: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  POOL_DISTRIBUTION_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  POOL_SHARES: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  VIP_DURATION: TypedContractMethod<[], [bigint], "view">;

  WITHDRAW_PERCENTAGES: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  activatePacket: TypedContractMethod<
    [_packetIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;

  claimMatrix: TypedContractMethod<[], [void], "nonpayable">;

  claimPool: TypedContractMethod<[], [void], "nonpayable">;

  completeMultisigTransition: TypedContractMethod<[], [void], "nonpayable">;

  confirmVip: TypedContractMethod<
    [_user: AddressLike, _starLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentPhase: TypedContractMethod<[], [bigint], "view">;

  deploymentTime: TypedContractMethod<[], [bigint], "view">;

  developmentFundWallet: TypedContractMethod<[], [string], "view">;

  distributePool: TypedContractMethod<[], [void], "nonpayable">;

  donateToPool: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  gamePoolWallet: TypedContractMethod<[], [string], "view">;

  getGovernanceInfo: TypedContractMethod<
    [],
    [
      [bigint, string, string, bigint, bigint] & {
        phase: bigint;
        currentOwner: string;
        pendingMultisigAddress: string;
        transitionCompletionTime: bigint;
        daysSinceDeployment: bigint;
      }
    ],
    "view"
  >;

  getMatrixNode: TypedContractMethod<
    [_nodeId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        user: string;
        parent: bigint;
        leftChild: bigint;
        rightChild: bigint;
        depth: bigint;
        leftCount: bigint;
        rightCount: bigint;
      }
    ],
    "view"
  >;

  getPoolInfo: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        [bigint, bigint, bigint, bigint, bigint],
        [bigint, bigint, bigint, bigint, bigint]
      ] & {
        poolBalance: bigint;
        nextDistributionTime: bigint;
        vipCounts: [bigint, bigint, bigint, bigint, bigint];
        poolShares: [bigint, bigint, bigint, bigint, bigint];
      }
    ],
    "view"
  >;

  getQueueInfo: TypedContractMethod<
    [],
    [[bigint, bigint] & { matrixQueueLength: bigint; poolQueueLength: bigint }],
    "view"
  >;

  getUserInfo: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        currentPacket: bigint;
        referrer: string;
        placementId: bigint;
        matrixBalance: bigint;
        poolBalance: bigint;
        totalEarned: bigint;
        isRegistered_: boolean;
      }
    ],
    "view"
  >;

  getVipInfo: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        starLevel: bigint;
        verifiedAt: bigint;
        expiresAt: bigint;
        daysLeft: bigint;
        isActive: boolean;
        antiSybilVerified: boolean;
        requiredPacket: bigint;
      }
    ],
    "view"
  >;

  getVipList: TypedContractMethod<
    [_starLevel: BigNumberish],
    [string[]],
    "view"
  >;

  initiateMultisigTransition: TypedContractMethod<
    [_multisigAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastPoolDistribution: TypedContractMethod<[], [bigint], "view">;

  liquidityPool: TypedContractMethod<[], [bigint], "view">;

  matrixNodes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        user: string;
        parent: bigint;
        leftChild: bigint;
        rightChild: bigint;
        depth: bigint;
        leftCount: bigint;
        rightCount: bigint;
        position: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  multisigTransitionTime: TypedContractMethod<[], [bigint], "view">;

  nextNodeId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingMultisig: TypedContractMethod<[], [string], "view">;

  performUpkeep: TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;

  reinvestFeeWallet: TypedContractMethod<[], [string], "view">;

  renewVip: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestVip: TypedContractMethod<
    [_starLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  reserveWallet: TypedContractMethod<[], [string], "view">;

  revokeVip: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  rootId: TypedContractMethod<[], [string], "view">;

  setAntiSybilVerified: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  totalMatrixPayouts: TypedContractMethod<[], [bigint], "view">;

  totalPoolPayouts: TypedContractMethod<[], [bigint], "view">;

  totalReferralPayouts: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWallets: TypedContractMethod<
    [
      _reinvestFeeWallet: AddressLike,
      _gamePoolWallet: AddressLike,
      _reserveWallet: AddressLike,
      _developmentFundWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint] & {
        currentPacket: bigint;
        referrer: string;
        placementId: bigint;
        matrixBalance: bigint;
        poolBalance: bigint;
        totalEarned: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  vipInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        starLevel: bigint;
        verifiedAt: bigint;
        expiresAt: bigint;
        antiSybilVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_REFERRAL_DEPTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WITHDRAW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PACKETS"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL_DISTRIBUTION_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL_SHARES"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "VIP_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WITHDRAW_PERCENTAGES"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "activatePacket"
  ): TypedContractMethod<[_packetIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimMatrix"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPool"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeMultisigTransition"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmVip"
  ): TypedContractMethod<
    [_user: AddressLike, _starLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deploymentTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "developmentFundWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributePool"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "donateToPool"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gamePoolWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGovernanceInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, string, string, bigint, bigint] & {
        phase: bigint;
        currentOwner: string;
        pendingMultisigAddress: string;
        transitionCompletionTime: bigint;
        daysSinceDeployment: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatrixNode"
  ): TypedContractMethod<
    [_nodeId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        user: string;
        parent: bigint;
        leftChild: bigint;
        rightChild: bigint;
        depth: bigint;
        leftCount: bigint;
        rightCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        [bigint, bigint, bigint, bigint, bigint],
        [bigint, bigint, bigint, bigint, bigint]
      ] & {
        poolBalance: bigint;
        nextDistributionTime: bigint;
        vipCounts: [bigint, bigint, bigint, bigint, bigint];
        poolShares: [bigint, bigint, bigint, bigint, bigint];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQueueInfo"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { matrixQueueLength: bigint; poolQueueLength: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        currentPacket: bigint;
        referrer: string;
        placementId: bigint;
        matrixBalance: bigint;
        poolBalance: bigint;
        totalEarned: bigint;
        isRegistered_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVipInfo"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        starLevel: bigint;
        verifiedAt: bigint;
        expiresAt: bigint;
        daysLeft: bigint;
        isActive: boolean;
        antiSybilVerified: boolean;
        requiredPacket: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVipList"
  ): TypedContractMethod<[_starLevel: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "initiateMultisigTransition"
  ): TypedContractMethod<[_multisigAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPoolDistribution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matrixNodes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        user: string;
        parent: bigint;
        leftChild: bigint;
        rightChild: bigint;
        depth: bigint;
        leftCount: bigint;
        rightCount: bigint;
        position: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "multisigTransitionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextNodeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingMultisig"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reinvestFeeWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renewVip"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestVip"
  ): TypedContractMethod<[_starLevel: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeVip"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rootId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAntiSybilVerified"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalMatrixPayouts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPoolPayouts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReferralPayouts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWallets"
  ): TypedContractMethod<
    [
      _reinvestFeeWallet: AddressLike,
      _gamePoolWallet: AddressLike,
      _reserveWallet: AddressLike,
      _developmentFundWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint] & {
        currentPacket: bigint;
        referrer: string;
        placementId: bigint;
        matrixBalance: bigint;
        poolBalance: bigint;
        totalEarned: bigint;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "vipInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        starLevel: bigint;
        verifiedAt: bigint;
        expiresAt: bigint;
        antiSybilVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AntiSybilVerified"
  ): TypedContractEvent<
    AntiSybilVerifiedEvent.InputTuple,
    AntiSybilVerifiedEvent.OutputTuple,
    AntiSybilVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "GovernancePhaseChanged"
  ): TypedContractEvent<
    GovernancePhaseChangedEvent.InputTuple,
    GovernancePhaseChangedEvent.OutputTuple,
    GovernancePhaseChangedEvent.OutputObject
  >;
  getEvent(
    key: "MatrixClaimed"
  ): TypedContractEvent<
    MatrixClaimedEvent.InputTuple,
    MatrixClaimedEvent.OutputTuple,
    MatrixClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MatrixPayout"
  ): TypedContractEvent<
    MatrixPayoutEvent.InputTuple,
    MatrixPayoutEvent.OutputTuple,
    MatrixPayoutEvent.OutputObject
  >;
  getEvent(
    key: "MultisigTransitionCompleted"
  ): TypedContractEvent<
    MultisigTransitionCompletedEvent.InputTuple,
    MultisigTransitionCompletedEvent.OutputTuple,
    MultisigTransitionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigTransitionStarted"
  ): TypedContractEvent<
    MultisigTransitionStartedEvent.InputTuple,
    MultisigTransitionStartedEvent.OutputTuple,
    MultisigTransitionStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PacketActivated"
  ): TypedContractEvent<
    PacketActivatedEvent.InputTuple,
    PacketActivatedEvent.OutputTuple,
    PacketActivatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolClaimed"
  ): TypedContractEvent<
    PoolClaimedEvent.InputTuple,
    PoolClaimedEvent.OutputTuple,
    PoolClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PoolDistributed"
  ): TypedContractEvent<
    PoolDistributedEvent.InputTuple,
    PoolDistributedEvent.OutputTuple,
    PoolDistributedEvent.OutputObject
  >;
  getEvent(
    key: "PoolDonated"
  ): TypedContractEvent<
    PoolDonatedEvent.InputTuple,
    PoolDonatedEvent.OutputTuple,
    PoolDonatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralPayout"
  ): TypedContractEvent<
    ReferralPayoutEvent.InputTuple,
    ReferralPayoutEvent.OutputTuple,
    ReferralPayoutEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VipConfirmed"
  ): TypedContractEvent<
    VipConfirmedEvent.InputTuple,
    VipConfirmedEvent.OutputTuple,
    VipConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "VipRenewed"
  ): TypedContractEvent<
    VipRenewedEvent.InputTuple,
    VipRenewedEvent.OutputTuple,
    VipRenewedEvent.OutputObject
  >;
  getEvent(
    key: "VipRequested"
  ): TypedContractEvent<
    VipRequestedEvent.InputTuple,
    VipRequestedEvent.OutputTuple,
    VipRequestedEvent.OutputObject
  >;
  getEvent(
    key: "VipRevoked"
  ): TypedContractEvent<
    VipRevokedEvent.InputTuple,
    VipRevokedEvent.OutputTuple,
    VipRevokedEvent.OutputObject
  >;

  filters: {
    "AntiSybilVerified(address)": TypedContractEvent<
      AntiSybilVerifiedEvent.InputTuple,
      AntiSybilVerifiedEvent.OutputTuple,
      AntiSybilVerifiedEvent.OutputObject
    >;
    AntiSybilVerified: TypedContractEvent<
      AntiSybilVerifiedEvent.InputTuple,
      AntiSybilVerifiedEvent.OutputTuple,
      AntiSybilVerifiedEvent.OutputObject
    >;

    "GovernancePhaseChanged(uint8,uint8)": TypedContractEvent<
      GovernancePhaseChangedEvent.InputTuple,
      GovernancePhaseChangedEvent.OutputTuple,
      GovernancePhaseChangedEvent.OutputObject
    >;
    GovernancePhaseChanged: TypedContractEvent<
      GovernancePhaseChangedEvent.InputTuple,
      GovernancePhaseChangedEvent.OutputTuple,
      GovernancePhaseChangedEvent.OutputObject
    >;

    "MatrixClaimed(address,uint256,uint256)": TypedContractEvent<
      MatrixClaimedEvent.InputTuple,
      MatrixClaimedEvent.OutputTuple,
      MatrixClaimedEvent.OutputObject
    >;
    MatrixClaimed: TypedContractEvent<
      MatrixClaimedEvent.InputTuple,
      MatrixClaimedEvent.OutputTuple,
      MatrixClaimedEvent.OutputObject
    >;

    "MatrixPayout(address,uint256)": TypedContractEvent<
      MatrixPayoutEvent.InputTuple,
      MatrixPayoutEvent.OutputTuple,
      MatrixPayoutEvent.OutputObject
    >;
    MatrixPayout: TypedContractEvent<
      MatrixPayoutEvent.InputTuple,
      MatrixPayoutEvent.OutputTuple,
      MatrixPayoutEvent.OutputObject
    >;

    "MultisigTransitionCompleted(address,uint256)": TypedContractEvent<
      MultisigTransitionCompletedEvent.InputTuple,
      MultisigTransitionCompletedEvent.OutputTuple,
      MultisigTransitionCompletedEvent.OutputObject
    >;
    MultisigTransitionCompleted: TypedContractEvent<
      MultisigTransitionCompletedEvent.InputTuple,
      MultisigTransitionCompletedEvent.OutputTuple,
      MultisigTransitionCompletedEvent.OutputObject
    >;

    "MultisigTransitionStarted(address,uint256)": TypedContractEvent<
      MultisigTransitionStartedEvent.InputTuple,
      MultisigTransitionStartedEvent.OutputTuple,
      MultisigTransitionStartedEvent.OutputObject
    >;
    MultisigTransitionStarted: TypedContractEvent<
      MultisigTransitionStartedEvent.InputTuple,
      MultisigTransitionStartedEvent.OutputTuple,
      MultisigTransitionStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PacketActivated(address,uint256,uint256)": TypedContractEvent<
      PacketActivatedEvent.InputTuple,
      PacketActivatedEvent.OutputTuple,
      PacketActivatedEvent.OutputObject
    >;
    PacketActivated: TypedContractEvent<
      PacketActivatedEvent.InputTuple,
      PacketActivatedEvent.OutputTuple,
      PacketActivatedEvent.OutputObject
    >;

    "PoolClaimed(address,uint256,uint256)": TypedContractEvent<
      PoolClaimedEvent.InputTuple,
      PoolClaimedEvent.OutputTuple,
      PoolClaimedEvent.OutputObject
    >;
    PoolClaimed: TypedContractEvent<
      PoolClaimedEvent.InputTuple,
      PoolClaimedEvent.OutputTuple,
      PoolClaimedEvent.OutputObject
    >;

    "PoolDistributed(uint256,uint256[5],uint256)": TypedContractEvent<
      PoolDistributedEvent.InputTuple,
      PoolDistributedEvent.OutputTuple,
      PoolDistributedEvent.OutputObject
    >;
    PoolDistributed: TypedContractEvent<
      PoolDistributedEvent.InputTuple,
      PoolDistributedEvent.OutputTuple,
      PoolDistributedEvent.OutputObject
    >;

    "PoolDonated(address,uint256)": TypedContractEvent<
      PoolDonatedEvent.InputTuple,
      PoolDonatedEvent.OutputTuple,
      PoolDonatedEvent.OutputObject
    >;
    PoolDonated: TypedContractEvent<
      PoolDonatedEvent.InputTuple,
      PoolDonatedEvent.OutputTuple,
      PoolDonatedEvent.OutputObject
    >;

    "ReferralPayout(address,address,uint256,bool)": TypedContractEvent<
      ReferralPayoutEvent.InputTuple,
      ReferralPayoutEvent.OutputTuple,
      ReferralPayoutEvent.OutputObject
    >;
    ReferralPayout: TypedContractEvent<
      ReferralPayoutEvent.InputTuple,
      ReferralPayoutEvent.OutputTuple,
      ReferralPayoutEvent.OutputObject
    >;

    "UserRegistered(address,address,uint256)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;

    "VipConfirmed(address,uint256,uint256)": TypedContractEvent<
      VipConfirmedEvent.InputTuple,
      VipConfirmedEvent.OutputTuple,
      VipConfirmedEvent.OutputObject
    >;
    VipConfirmed: TypedContractEvent<
      VipConfirmedEvent.InputTuple,
      VipConfirmedEvent.OutputTuple,
      VipConfirmedEvent.OutputObject
    >;

    "VipRenewed(address,uint256,uint256)": TypedContractEvent<
      VipRenewedEvent.InputTuple,
      VipRenewedEvent.OutputTuple,
      VipRenewedEvent.OutputObject
    >;
    VipRenewed: TypedContractEvent<
      VipRenewedEvent.InputTuple,
      VipRenewedEvent.OutputTuple,
      VipRenewedEvent.OutputObject
    >;

    "VipRequested(address,uint256)": TypedContractEvent<
      VipRequestedEvent.InputTuple,
      VipRequestedEvent.OutputTuple,
      VipRequestedEvent.OutputObject
    >;
    VipRequested: TypedContractEvent<
      VipRequestedEvent.InputTuple,
      VipRequestedEvent.OutputTuple,
      VipRequestedEvent.OutputObject
    >;

    "VipRevoked(address)": TypedContractEvent<
      VipRevokedEvent.InputTuple,
      VipRevokedEvent.OutputTuple,
      VipRevokedEvent.OutputObject
    >;
    VipRevoked: TypedContractEvent<
      VipRevokedEvent.InputTuple,
      VipRevokedEvent.OutputTuple,
      VipRevokedEvent.OutputObject
    >;
  };
}
